server:
  port: 6003
spring:
  application:
    name: fari-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacospassword
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/fariblog
      username: omnitrix
      password: dbpassword