#server:
#  port: 6002


#client:
#  id: fari-gateway
#  secret: fari-gateway-20201030
#  redirect-uri: http://localhost:8501/fariblog/loginy

security:
  oauth2:
    client:
      client-id: fari-gateway
      client-secret: fari-gateway-20201030
      user-authorization-uri: http://localhost:6002/fari-auth/oauth/authorize
      access-token-uri: http://localhost:6002/fari-auth/oauth/token