server:
  port: 6001

client:
  client-id: FARI_GATEWAY

spring:
  application:
    name: fari-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

datasource:
  url: jdbc:mysql://81.71.139.43:3306
  username: omnitrix
  password: 981017
  hikari:
    connection-timeout: 30000
    idle-timeout: 600000


